version: 0.2

phases:
  install:
    commands:
      - python3 -m venv ./fprime-venv
      - . ./fprime-venv/bin/activate
      - pip3 install --upgrade wheel setuptools pip
      - pip3 install ./Fw/Python
      - pip3 install ./Gds
      - yum -y install gcc
      - wget https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6.tar.gz
      - tar -xvzf cmake-3.19.6.tar.gz
      - cd cmake-3.19.6
      - ./bootstrap
      - make
      - make install
      - cd ..
  build:
    commands:
      - cd Ref
      - fprime-util generate
      - fprime-util build --jobs 32
      - fprime-util install --jobs 32