version: 0.2

phases:
  install:
    commands:
      - python3 -m venv ./fprime-venv
      - . ./fprime-venv/bin/activate
      - pip install --upgrade wheel setuptools pip
      - pip install ./Fw/Python
      - pip install ./Gds
      - wget https://github.com/Kitware/CMake/releases/download/v3.20.0-rc4/cmake-3.20.0-rc4-linux-x86_64.sh
      - chmod 777 cmake-3.20.0-rc4-linux-x86_64.sh
      - ./cmake-3.20.0-rc4-linux-x86_64.sh
  build:
    commands:
      - cd Ref
      - fprime-util generate
      - fprime-util build --jobs 32
      - fprime-util install --jobs 32